sudo: required
services:
  - docker
cache:
  directories:
    - node_modules

before_install:
  - docker build -t zakul2aa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zakul2aa/docker-react npm run test
